starting to clean things up

diff --git a/.github/workflows/node-test.yml b/.github/workflows/node-test.yml
--- a/.github/workflows/node-test.yml
+++ b/.github/workflows/node-test.yml
@@ -8,99 +8,100 @@ env:
   CI: true
 
 jobs:
-  # lint:
-  #   runs-on: ubuntu-latest
-  #   if: github.event_name == 'pull_request'
-  #   strategy:
-  #     matrix:
-  #       node-version:
-  #         - "16"
-  #   steps:
-  #     - uses: actions/checkout@v3
-  #       with:
-  #         fetch-depth: 0
-  #     - uses: actions/setup-node@v3
-  #       with:
-  #         node-version: ${{ matrix.node-version }}
-  #         cache: npm
-  #         cache-dependency-path: npm-shrinkwrap.json
+  lint:
+    runs-on: ubuntu-latest
+    if: github.event_name == 'pull_request'
+    strategy:
+      matrix:
+        node-version:
+          - "16"
+    steps:
+      - uses: actions/checkout@v3
+        with:
+          fetch-depth: 0
+      - uses: actions/setup-node@v3
+        with:
+          node-version: ${{ matrix.node-version }}
+          cache: npm
+          cache-dependency-path: npm-shrinkwrap.json
 
-  #     - run: npm i -g npm@8.7
-  #     - run: npm ci
-  #     - run: npm run lint:changed-files
+      - run: npm i -g npm@8.7
+      - run: npm ci
+      - run: npm run lint:changed-files
 
-  # unit:
-  #   runs-on: ubuntu-latest
-  #   strategy:
-  #     matrix:
-  #       node-version:
-  #         - "14"
-  #         - "16"
-  #         - "18"
-  #   steps:
-  #     - uses: actions/checkout@v3
-  #     - uses: actions/setup-node@v3
-  #       with:
-  #         node-version: ${{ matrix.node-version }}
-  #         cache: npm
-  #         cache-dependency-path: npm-shrinkwrap.json
+  unit:
+    runs-on: ubuntu-latest
+    strategy:
+      matrix:
+        node-version:
+          - "14"
+          - "16"
+          - "18"
+    steps:
+      - uses: actions/checkout@v3
+      - uses: actions/setup-node@v3
+        with:
+          node-version: ${{ matrix.node-version }}
+          cache: npm
+          cache-dependency-path: npm-shrinkwrap.json
 
-  #     - run: npm i -g npm@8.7
-  #     - run: npm ci
-  #     - run: npm test
+      - run: npm i -g npm@8.7
+      - run: npm ci
+      - run: npm test
 
-  # integration:
-  #   needs: unit
-  #   if: github.event_name == 'push'
-  #   runs-on: ubuntu-latest
+  integration:
+    needs: unit
+    if: github.event_name == 'push'
+    runs-on: ubuntu-latest
 
-  #   env:
-  #     FIREBASE_CLI_PREVIEWS: none
-  #     FIREBASE_EMULATORS_PATH: ${{ github.workspace }}/emulator-cache
-  #     COMMIT_SHA: ${{ github.sha }}
-  #     CI_JOB_ID: ${{ github.action }}
-  #     FBTOOLS_TARGET_PROJECT: ${{ secrets.FBTOOLS_TARGET_PROJECT }}
-  #     FBTOOLS_CLIENT_INTEGRATION_SITE: ${{ secrets.FBTOOLS_CLIENT_INTEGRATION_SITE }}
+    env:
+      FIREBASE_CLI_PREVIEWS: none
+      FIREBASE_EMULATORS_PATH: ${{ github.workspace }}/emulator-cache
+      COMMIT_SHA: ${{ github.sha }}
+      CI_JOB_ID: ${{ github.action }}
+      FBTOOLS_TARGET_PROJECT: ${{ secrets.FBTOOLS_TARGET_PROJECT }}
+      FBTOOLS_CLIENT_INTEGRATION_SITE: ${{ secrets.FBTOOLS_CLIENT_INTEGRATION_SITE }}
 
-  #   strategy:
-  #     fail-fast: false
-  #     matrix:
-  #       node-version:
-  #         - "16"
-  #       script:
-  #         - npm run test:hosting
-  #         - npm run test:client-integration
-  #         - npm run test:emulator
-  #         - npm run test:import-export
-  #         - npm run test:extensions-emulator
-  #         - npm run test:triggers-end-to-end
-  #         - npm run test:storage-deploy
-  #         - npm run test:storage-emulator-integration
-  #   steps:
-  #     - uses: actions/checkout@v3
-  #     - uses: actions/setup-node@v3
-  #       with:
-  #         node-version: ${{ matrix.node-version }}
-  #         cache: npm
-  #         cache-dependency-path: npm-shrinkwrap.json
+    strategy:
+      fail-fast: false
+      matrix:
+        node-version:
+          - "16"
+        script:
+          - npm run test:hosting
+          - npm run test:client-integration
+          - npm run test:emulator
+          - npm run test:import-export
+          - npm run test:extensions-emulator
+          - npm run test:triggers-end-to-end
+          - npm run test:storage-deploy
+          - npm run test:storage-emulator-integration
+    steps:
+      - uses: actions/checkout@v3
+      - uses: actions/setup-node@v3
+        with:
+          node-version: ${{ matrix.node-version }}
+          cache: npm
+          cache-dependency-path: npm-shrinkwrap.json
 
-  #     - name: Cache firebase emulators
-  #       uses: actions/cache@v3
-  #       with:
-  #         path: ${{ env.FIREBASE_EMULATORS_PATH }}
-  #         key: ${{ runner.os }}-firebase-emulators-${{ hashFiles('emulator-cache/**') }}
-  #       continue-on-error: true
+      - name: Cache firebase emulators
+        uses: actions/cache@v3
+        with:
+          path: ${{ env.FIREBASE_EMULATORS_PATH }}
+          key: ${{ runner.os }}-firebase-emulators-${{ hashFiles('emulator-cache/**') }}
+        continue-on-error: true
 
-  #     - run: npm i -g npm@8.7
-  #     - run: npm ci
-  #     - run: echo ${{ secrets.service_account_json_base64 }} | base64 -d > ./scripts/service-account.json
-  #     - run: ${{ matrix.script }}
+      - run: npm i -g npm@8.7
+      - run: npm ci
+      - run: echo ${{ secrets.service_account_json_base64 }} | base64 -d > ./scripts/service-account.json
+      - run: ${{ matrix.script }}
 
-  #     - name: Print debug logs
-  #       if: failure()
-  #       run: find . -type f -name "*debug.log" | xargs cat
+      - name: Print debug logs
+        if: failure()
+        run: find . -type f -name "*debug.log" | xargs cat
 
   integration-windows:
+    needs: unit
     if: github.event_name == 'push'
     runs-on: windows-latest
 
@@ -118,13 +119,13 @@ jobs:
         node-version:
           - "16"
         script:
-        #   - npm run test:hosting
-        #   - npm run test:client-integration
-        #   - npm run test:emulator
-          # - npm run test:import-export
-          - npm run test:extensions-emulator
-          # - npm run test:triggers-end-to-end
-          # - npm run test:storage-deploy
+          - npm run test:hosting
+          - npm run test:client-integration
+          - npm run test:emulator
+          - npm run test:import-export
+          # - npm run test:extensions-emulator # Fails due to cannot find module sharp (not waiting for npm install?)
+          - npm run test:triggers-end-to-end
+          - npm run test:storage-deploy
           # - npm run test:storage-emulator-integration
     steps:
       - name: Setup Java JDK
@@ -152,48 +153,48 @@ jobs:
       - run: npm i -g npm@8.7
       - run: npm ci
       - run: ${{ matrix.script }}
-
+      - run: dir
       - name: Print debug logs
         if: failure()
         run: type *debug.log
 
-  # check-package-lock:
-  #   runs-on: ubuntu-latest
+  check-package-lock:
+    runs-on: ubuntu-latest
 
-  #   strategy:
-  #     matrix:
-  #       node-version:
-  #         - "16"
+    strategy:
+      matrix:
+        node-version:
+          - "16"
 
-  #   steps:
-  #     - uses: actions/checkout@v3
-  #     - name: Use Node.js ${{ matrix.node-version }}
-  #       uses: actions/setup-node@v3
-  #       with:
-  #         node-version: ${{ matrix.node-version }}
-  #         cache: npm
-  #         cache-dependency-path: npm-shrinkwrap.json
-  #     - run: npm i -g npm@8.7
-  #     # --ignore-scripts prevents the `prepare` script from being run.
-  #     - run: npm install --package-lock-only --ignore-scripts
-  #     - run: "git diff --exit-code -- npm-shrinkwrap.json || (echo 'Error: npm-shrinkwrap.json is changed during npm install! Please make sure to use npm >= 8 and commit npm-shrinkwrap.json.' && false)"
+    steps:
+      - uses: actions/checkout@v3
+      - name: Use Node.js ${{ matrix.node-version }}
+        uses: actions/setup-node@v3
+        with:
+          node-version: ${{ matrix.node-version }}
+          cache: npm
+          cache-dependency-path: npm-shrinkwrap.json
+      - run: npm i -g npm@8.7
+      # --ignore-scripts prevents the `prepare` script from being run.
+      - run: npm install --package-lock-only --ignore-scripts
+      - run: "git diff --exit-code -- npm-shrinkwrap.json || (echo 'Error: npm-shrinkwrap.json is changed during npm install! Please make sure to use npm >= 8 and commit npm-shrinkwrap.json.' && false)"
 
-  # check-json-schema:
-  #   runs-on: ubuntu-latest
+  check-json-schema:
+    runs-on: ubuntu-latest
 
-  #   strategy:
-  #     matrix:
-  #       node-version:
-  #         - "16"
+    strategy:
+      matrix:
+        node-version:
+          - "16"
 
-  #   steps:
-  #     - uses: actions/checkout@v3
-  #     - name: Use Node.js ${{ matrix.node-version }}
-  #       uses: actions/setup-node@v3
-  #       with:
-  #         node-version: ${{ matrix.node-version }}
-  #         cache: npm
-  #         cache-dependency-path: npm-shrinkwrap.json
-  #     - run: npm install
-  #     - run: npm run generate:json-schema
-  #     - run: "git diff --exit-code -- schema/*.json || (echo 'Error: JSON schema is changed! Please run npm run generate:json-schema and commit the results.' && false)"
+    steps:
+      - uses: actions/checkout@v3
+      - name: Use Node.js ${{ matrix.node-version }}
+        uses: actions/setup-node@v3
+        with:
+          node-version: ${{ matrix.node-version }}
+          cache: npm
+          cache-dependency-path: npm-shrinkwrap.json
+      - run: npm install
+      - run: npm run generate:json-schema
+      - run: "git diff --exit-code -- schema/*.json || (echo 'Error: JSON schema is changed! Please run npm run generate:json-schema and commit the results.' && false)"
